CREATE TABLE IF NOT EXISTS tb_order_producer
(
    ID                  SERIAL    NOT NULL,
    IDENTIFY           VARCHAR   NOT NULL,
    CREATED_AT         TIMESTAMP NOT NULL,
    LIMIT_DELIVERY_DATE INTEGER   DEFAULT NULL,
    DELIVERY_DATE       TIMESTAMP NOT NULL,
    CORPORATE_NAME     VARCHAR   NULL DEFAULT NULL,
    NAME               VARCHAR   NOT NULL,
    CPF                VARCHAR   NOT NULL,
    CNPJ               VARCHAR   NOT NULL,
    ADDRESS            VARCHAR   NULL DEFAULT NULL,
    COMMENTS           TEXT      NULL DEFAULT NULL,
    BOX_TYPE            VARCHAR   NOT NULL,
    RESPONSIBLE         VARCHAR   NULL DEFAULT NULL,
    SERVICE_GRANTOR     VARCHAR   NULL DEFAULT NULL,
    SHIPPING_FOR_PRODUCTION BOOLEAN DEFAULT NULL,
    BOX_BODY_ID         INTEGER NOT NULL,
    ORDER_STATUS_ID     INTEGER NOT NULL,
    PAYMENT_ID          INTEGER NOT NULL,
    PRIMARY KEY (ID)
);


CREATE TABLE IF NOT EXISTS tb_box_body
(
    ID                SERIAL  NOT NULL,
    LENGTH             INTEGER NOT NULL,
    WIDTH            INTEGER NOT NULL,
    HEIGHT          INTEGER NOT NULL,
    VALUE_LENGTH_CALC  INTEGER NOT NULL,
    VALUE_WIDTH_CALC   INTEGER NOT NULL,
    VALUE_HEIGHT_CALC  INTEGER NOT NULL,
    VALUE_ABA_SUP      INTEGER DEFAULT NULL,
    VALUE_ABA_SUB      INTEGER DEFAULT NULL,
    DILATED_LENGTH_ONE INTEGER NOT NULL,
    DILATED_WIDTH_ONE  INTEGER NOT NULL,
    DILATED_LENGTH_TWO INTEGER NOT NULL,
    DILATED_WIDTH_TWO  INTEGER NOT NULL,
    DILATED_HEIGHT     INTEGER NOT NULL,
    DILATED_ABAS_SUP   INTEGER NOT NULL,
    DILATED_ABAS_SUB   INTEGER NOT NULL,
    PRIMARY KEY (ID)
);


DO
$$
    BEGIN IF NOT EXISTS(SELECT 1
                        FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE
                        WHERE CONSTRAINT_NAME = 'fk_tb_order_producer_box_body_id') THEN
        ALTER TABLE tb_order_producer
            ADD CONSTRAINT FK_TB_ORDER_PRODUCER_BOX_BODY_ID FOREIGN KEY (BOX_BODY_ID)
                REFERENCES TB_BOX_BODY (ID)
                ON DELETE RESTRICT ON UPDATE RESTRICT;
    END IF;
    END;
$$;


CREATE TABLE IF NOT EXISTS tb_payment
(
    ID SERIAL NOT NULL,
    NAME VARCHAR DEFAULT NULL,
    CPF  VARCHAR NOT NULL,
    PAY_TYPE VARCHAR NOT NULL,
    PRODUCT_TYPE VARCHAR NOT NULL,
    PRODUCT_VALUE DECIMAL(12,2),
    APPROVED_PAYMENT BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (ID)
);


CREATE TABLE IF NOT EXISTS tb_order_status
(
    ID SERIAL NOT NULL,
    IDENTIFY VARCHAR DEFAULT NULL,
    STATUSNAME VARCHAR NOT NULL,
    DESCRIPTION VARCHAR NOT NULL,
    HEXACOLOR VARCHAR(10) NOT NULL,
    POSITION INTEGER NOT NULL,
    PRIMARY KEY (ID)
);


DO
$$
    BEGIN IF NOT EXISTS(SELECT 1
                        FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE
                        WHERE CONSTRAINT_NAME = 'fk_tb_order_producer_payment_id') THEN
        ALTER TABLE TB_ORDER_PRODUCER
            ADD CONSTRAINT FK_TB_ORDER_PRODUCER_PAYMENT_ID FOREIGN KEY (PAYMENT_ID)
                REFERENCES TB_PAYMENT (ID)
                ON DELETE RESTRICT ON UPDATE RESTRICT;
    END IF;
    END;
$$;

DO
$$
    BEGIN IF NOT EXISTS(SELECT 1
                        FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE
                        WHERE CONSTRAINT_NAME = 'fk_tb_order_producer_order_status_id') THEN
        ALTER TABLE TB_ORDER_PRODUCER
            ADD CONSTRAINT FK_TB_ORDER_PRODUCER_ORDER_STATUS_ID FOREIGN KEY (ORDER_STATUS_ID)
                REFERENCES TB_ORDER_STATUS (ID)
                ON DELETE RESTRICT ON UPDATE RESTRICT;
    END IF;
    END;
$$;