version: '3.1'
services:
  db:
    image: postgres
    container_name: db-controller
    environment:
      POSTGRES_ROO_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTEGRES_DB: db-controller
    ports:
      - "5431:5432"
    volumes:
      - db-controller/var/lib/postgres
volumes:
  db-controller: