version: '3.1'
services:
  db:
    image: postgres
    container_name: db-service
    environment:
      POSTGRES_ROO_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTEGRES_DB: db-producer
    ports:
      - "5430:5432"
    volumes:
      - db-service/var/lib/postgres
volumes:
  db-service: